export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';



export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_LOADING = 'REMOVE_TODO_LOADING';
export const REMOVE_TODO_FAIL = 'REMOVE_TODO_FAIL';




export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_LOADING = 'UPDATE_TODO_LOADING';
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL';



